###
@hostname = localhost
###

# @name resp
GET http://{{hostname}}:8082/topics HTTP/1.1
Accept: application/vnd.kafka.v2+json

###

# @name resp
GET http://{{hostname}}:8082/topics/docker-connect-status HTTP/1.1
Accept: application/vnd.kafka.v2+json

###

@myvar = {{resp.response.body.prop1}}
###

POST {{myvar}}